{
  "openapi": "3.0.0",
  "info": {
    "title": "Box API",
    "description": "The Box Content API gives you access to secure content management and content experience features for use in your own app.",
    "version": "2.0.0",
    "contact": {
      "name": "Box Developer Support",
      "url": "https://developer.box.com",
      "email": "developers@box.com"
    }
  },
  "servers": [
    {
      "url": "https://api.box.com/2.0"
    }
  ],
  "paths": {
    "/folders/{folder_id}": {
      "get": {
        "summary": "Get folder information",
        "description": "Retrieves details for a specific folder.",
        "security": [
          {
            "OAuth2": [
              "root_readonly"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update folder",
        "description": "Updates information for a folder.",
        "security": [
          {
            "OAuth2": [
              "root_readwrite"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete folder",
        "description": "Deletes a folder.",
        "security": [
          {
            "OAuth2": [
              "root_readwrite"
            ]
          }
        ]
      }
    },
    "/folders": {
      "post": {
        "summary": "Create folder",
        "description": "Creates a new folder.",
        "security": [
          {
            "OAuth2": [
              "root_readwrite"
            ]
          }
        ]
      }
    },
    "/files/{file_id}": {
      "get": {
        "summary": "Get file information",
        "description": "Retrieves details for a specific file.",
        "security": [
          {
            "OAuth2": [
              "root_readonly"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update file",
        "description": "Updates information for a file.",
        "security": [
          {
            "OAuth2": [
              "root_readwrite"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete file",
        "description": "Deletes a file.",
        "security": [
          {
            "OAuth2": [
              "root_readwrite"
            ]
          }
        ]
      }
    },
    "/files/{file_id}/content": {
      "get": {
        "summary": "Download file",
        "description": "Retrieves the actual data of the file.",
        "security": [
          {
            "OAuth2": [
              "root_readonly"
            ]
          }
        ]
      }
    },
    "/files/content": {
      "post": {
        "summary": "Upload file",
        "description": "Uploads a new file.",
        "security": [
          {
            "OAuth2": [
              "root_readwrite"
            ]
          }
        ]
      }
    },
    "/users": {
      "get": {
        "summary": "List enterprise users",
        "description": "Returns a list of all users for the Enterprise along with their user_id, public_name, and login.",
        "security": [
          {
            "OAuth2": [
              "manage_enterprise"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create user",
        "description": "Creates a new managed user in an enterprise.",
        "security": [
          {
            "OAuth2": [
              "manage_enterprise"
            ]
          }
        ]
      }
    },
    "/users/{user_id}": {
      "get": {
        "summary": "Get user information",
        "description": "Retrieves information about a user in the enterprise.",
        "security": [
          {
            "OAuth2": [
              "manage_enterprise"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update user",
        "description": "Updates information about a user in the enterprise.",
        "security": [
          {
            "OAuth2": [
              "manage_enterprise"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete user",
        "description": "Deletes a user in the enterprise.",
        "security": [
          {
            "OAuth2": [
              "manage_enterprise"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://account.box.com/api/oauth2/authorize",
            "tokenUrl": "https://api.box.com/oauth2/token",
            "scopes": {
              "root_readonly": "Read all files and folders stored in Box",
              "root_readwrite": "Read and write all files and folders stored in Box",
              "manage_enterprise": "Manage an enterprise"
            }
          }
        }
      }
    }
  }
}